### ISSUE TITLE
AC:   I can enter my contact information on the new Volunteer screen

### ISSUE THREAD

**Issue by sppatel75** [NorthBridge/nexus-community#109]

**Comment by sppatel75** [comment]
Issue:  When I enter in a invalid email address the error message over writes my input and I'm forced to retype my email address.

**Comment by sppatel75** [comment]
Issue:  When I select "Server side Validation"  I get blank screen.
Using FireFox.

**Comment by sppatel75** [comment]
issue"  when I "Server side Validation" and input a invalid email address, a new page appears with error message:Invalid state on email. 

![error-email](https://cloud.githubusercontent.com/assets/6797839/6100485/79ec88ea-afd6-11e4-9c3d-16736ea55a17.png)

**Comment by sppatel75** [comment]
issue:  I can enter is XSS in "Tell us about your self" Box.  <script type='text/javascript'>alert('pwnd');</script>

**Comment by sppatel75** [comment]
Enhancement request:

When I start typing in the "Other" text box, and do not have the check box checked, can we automatically check the check box?

**Comment by kdflint** [comment]
It is by design that a bad email address is blanked out, replaced by the error message. This is because it's a very compact form and we are using the form fields to show errors instead of having separate screen space for errors.

Blank screen issue fixed.

Server side validation error message shows on a new page by design. Success however will display on the form.

I have implemented the auto-check on the "Other" checkboxes but it's imperfect because the check will then remain if the user backspaces and erases their input. To to this *exactly* right takes more time than I have! See if what I did is acceptable...

**Comment by gretchiesprite** [comment]
The check box works when I start typing in the other fields. I also noticed that the name and other fields will accept only numerical inputs. Also, I can enter only my name and email address and get no errors. Should we require at least one of the boxes for "What would you like to get from your volunteer work with Northbridge?" and "What is your expertise?" be checked?

**Comment by kdflint** [comment]
Thanks Gretchen!

As we deliberated on the stand-up, let's leave it as acceptable for only
digits on a name. There is a length limit (25, I think)

On the email, the front side only does very basic validation and will let
all digits through. The back side though uses the PHP email filter library
and it does choke on  "111@222.333" and "1112223333". If someone attempts
an email like that they are definitely up to no good so I don't even give a
nice user message, just log it along with ip address.

Also, I decided to leave the skills and motivations optional, just because
I want to make the bar as low as possible for submitting the form. If
someone does not want to give us this info. for whatever reason, let's not
force it. We will be following up for a conversation anyway and can enter
later.

taa

Kathy

-- 



*Kathy Flint, CEO NorthBridge Technology Alliance
http://NorthBridgeTech.org <http://NorthBridgeTech.org>
Kathy.Flint@NorthBridgeTech.org *
