### ISSUE TITLE
Landing Page - Session not expiring if "Remember Me" checkbox not set in IE

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#157]
In Internet Explorer, the session does not expire after 5 minutes -- I can still perform actions in the landing page.

**Comment by kdflint** [comment]
Try these steps please:

Login (w/o remember)

Wait 5 minutes (or 6 or 7 to be sure)

Click Team, User Profile - you'll still be ok as all this is pre-loaded

Try to enter a new meeting reservation or just Ctrl-R - Now you SHOULD get bounced back to login screen. If not there is definitely a problem.

Background: The server always determines if the session is still good before it serves anything new up. The client calls to the server every minute to record user activity. But we don't maintain a timer on the client side because I think client side security measures mostly silly.

**Comment by kcavness** [comment]
Following your test instructions, I re-tested this and it now works.
