### ISSUE TITLE
A date in the past is allowed to be created with no error message displayed

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#163]
It should not be possible to create a room reservation for a date in the past.

**Comment by kdflint** [comment]
Now, if the date and times are actually valid pieces of data, we check that now > reservation time, using the epoch for comparison.

NOTE!!! This is a remaining bug .... the epoch calculation for the reservation time is done using system timezone, not the timezone that the user may have selected.

I have opened a new issue for this because I need to think about best design and I want someone to go ahead and hammer on this much.

**Comment by gretchiesprite** [comment]
This works, with the exception of the bug that we already know about. Closing now.
