### ISSUE TITLE
Internet Explorer: Start Now functionality does not open new room

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#183]
Meeting Name: Kenneth Room Reservation Test 1 (and 2, and 11)
Meeting Type: Collaboration
Duration: 1 Hour

Clicked on "Open Room", but nothing happened.

**Comment by kdflint** [comment]
What SHOULD happen is that you first get a form to enter a couple details. Then you say Open Room which really just inserts a new reservation for now(). Your new reservation for now will appear at the top of the schedule. Then you have to click on the arrow icon to actually join the room that you just "opened."

I think it may not be intuitive... I bet you didn't click the arrow icon...

**Comment by kdflint** [comment]
Um, nevermind. I ran smack into this doing a client demo today! As you said, you click Open Room but nothing happens :)

**Comment by kcavness** [comment]
On the one hand, glad you were able to duplicate it... on the other... ;-)

**Comment by kdflint** [comment]
This form and the "reserve room in the future" form share the same validation javascript. This form uses some hidden fields to supply the values that it doesn't need to collect from the user. The date input is one of those (since the meeting is for now). The validation script was not prepared for the constant string input and validation failed BUT since the field is hidden there was no feedback to the user.

Not sure why I feel compelled to explain what the bug was but it is somehow satisfying so I do :)

**Comment by kcavness** [comment]
Verified that this now works.
