### ISSUE TITLE
Using the guest pass and entering an email in the Name field causes an XML error.

### ISSUE THREAD

**Issue by kcavness** [NorthBridge/nexus-community#302]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<returncode>FAILED</returncode>
<messageKey>missingParamFullName</messageKey>
<message>
You must specify a name for the attendee who will be joining the meeting.
</message>
</response>

![image](https://cloud.githubusercontent.com/assets/5615067/15878148/8fe80c76-2ccd-11e6-8b8e-5facf2e14561.png)

**Comment by kdflint** [comment]
Great catch Kenneth!

Problem was the A in AJAX.

The meeting join processor looks to a session value on the server for the username. Why? because we use the same mechanism to join the meeting for guest users as we do for authenticated users.

Anyway, if SESSION is not updated with that form name value by means of AJAX, before the call executes to join the meeting, then this error occurs. To fix, I have made the call synchronous (though this is often not recommended due to UXP perils)

Seems to be working. Can I get a code review on the new code?

If this method returns true, we go forward with the joinMeeting process. Otherwise we ask user to try again. Does this look foolproof?

```
function setPublicSession(oid, fname, mid, relativePath) {
	var xmlhttp = getXmlHttpRequest();
	var returnStatus;
	xmlhttp.onreadystatechange=function() {
		console.log(xmlhttp.readyState);
		if (xmlhttp.readyState == 4) {
			if (xmlhttp.status != 200) { 
				returnStatus = false;
			} else {
			 	returnStatus = true;
			}
		}
	};
	xmlhttp.open("GET", relativePath + "plugin/setPublicSession.php?oid=" + oid + "&timezone=" + getLocalTz() + "&fname=" + fname + "&uuid=" + mid, false);
	xmlhttp.send();
	return returnStatus;
}
```

**Comment by kcavness** [comment]
Insofar as I know code-y mc-codeface things on AJAX, this looks fine. Of
course, I don't know exactly how you code the service via that PHP page ;-)
