### ISSUE TITLE
Let user language selection toggle one word or phrase

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#311]
developer's choice - maybe something in the user profile?

**Comment by kdflint** [comment]
Toggling the Hello phrase next to the user first name

English: ![screenshot from 2016-10-11 17 28 09](https://cloud.githubusercontent.com/assets/1907202/19291035/6a8ab546-8fd8-11e6-8e83-376265b36191.png)

Spanish: ![screenshot from 2016-10-11 17 27 52](https://cloud.githubusercontent.com/assets/1907202/19291043/6f822ca0-8fd8-11e6-9eb7-f8580cde1d97.png)

**Comment by kdflint** [comment]
The use case that is ready to test: 

Login to the app. Should see the Hello phrase according to your browser preference. Must have NO English options on your list to see Spanish.

Change your preference. Should see the change render by means of a page reload.

Not implemented yet: Persisting preference across sessions. Once you log out or time out, you start over.

Also not implemented yet: Login screen, per #310

**Comment by kcavness** [comment]
I...don't know if I can test this validly without clearing out my cookies. I changed my browser settings so that Spanish was the only possible language, logged in, and it still gave me "Hello Kenneth" -- but that was because I had already chosen the site language of English in an earlier test. I switched to espanol in the dropdown and logged out entirely, then came back in, and it showed me Spanish (Hola Kenneth), but I think I may still have been going off of the cookie from the dropdown and not from the autoselection.

**Comment by gretchiesprite** [comment]
I forget which site is the test site (sorry!) but I checked these two:
http://northbridgetech.org/apps/nexus/web/nexus.php
http://northbridgetech.org/dev/nexus/web/nexus.php

At the first one, I got Hello Gretchen even after I cleared everything in IE.

On the second one, I just got Gretchen on both.

**Comment by gretchiesprite** [comment]
Sorry for all the comments/edits. I was completely derpy and was trying to change language via the browser. This works for me now and I'll stop commenting. :)

**Comment by kdflint** [comment]
OK, so, we aren't persisting the user's preference yet with cookies. It is stored in session and will be remembered as long as a session is alive.

Log out always kills the session.

if you have only the "es" option in your browser language list, AND you have logged out of Nexus Web Meet, you should see "Hola" after re-login. Always. So Kenneth - with that info... do you think there is a problem??
