### ISSUE TITLE
Created meeting doesnt display under future for non admin account 

### ISSUE THREAD

**Issue by Hema-Nambi** [NorthBridge/nexus-community#506]
1. Log in to a non admin account 
2. Create a meeting under future or now tile

Expected  : Created meeting should be displayed under future or now tile accordingly

Issue : Created meeting does not display under the future tile or now tile 

[Created_meeting_do_not__get_displayed .docx](https://github.com/NorthBridge/nexus-community/files/1352652/Created_meeting_do_not__get_displayed.docx)

**Comment by kdflint** [comment]
The cause of the problem was scheduleProcessor.php:59. 

A change was recently added to apply meetings state of pending if the meeting adder is not an administrator. However, this rule should not apply for Nexus Web Meet, only for Nexus Advantage and Nexus Public.

Fix created the necessary exception for NWM so now all meetings are displaying in the list as they should.
