### ISSUE TITLE
Read the documentation about this error

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/nexus-community#582]
and determine if we can fix

**Comment by Hema-Nambi** [comment]
This error means the requested operation cannot be performed in full-screen mode. It hampers your ability to run your desired program on Windows PC.

**Comment by Hema-Nambi** [comment]
And yes this issue can be fixed by either manually or using tool.

Manual Fix : 

1) Start your computer and log on as an administrator.

2) Click the Start button then select All Programs, Accessories, System Tools, and then click System Restore.

3) In the new window, select "Restore my computer to an earlier time" option and then click Next.

4) Select the most recent system restore point from the "On this list, click a restore point" list, and then click Next.

5) Click Next on the confirmation window.

6) Restarts the computer when the restoration is finished.
  

Tool Fix : 
1) Download (Error 1007) repair utility.

2) Install program and click Scan button.

3) Click the Fix Errors button when scan is completed.

4) Restart your computer.

**Comment by Hema-Nambi** [comment]
For further details on this error please check the below link
 https://errortools.com/windows/fix-error-1007/
