### ISSUE TITLE
Solve meeting join problem in DEV, which is related to formatting a custom Chat message on meeting join. (HTML)

### ISSUE THREAD

**Issue by kswens1** [NorthBridge/nexus-community#615]
When you join a BigBlueButton page see a custom page. Include Northbridge detail (link to site, phone number, logos.
Working in prod, but want it to perform the same in DEV

P: 1
E: 5

AC: Meeting creation call should never surface response in browser.
Note: Use curl implementation rather than inline request/response?

**Comment by kdflint** [comment]
Have made progress. DEV is no longer broken but we still don't have the custom welcome message that I want.

I am going to try one more time to put the custom welcome message...

**Comment by kdflint** [comment]
Now there is a custom welcome message. To test in DEV

Make a meeting and join it. In the Chat window, now you should see a sentence that says "This meting is brought to you by..." It includes the dial-in number and pin. 

NOTE: Unfortunately the dial-in number is NOT properly formatted here like it is on our Guest page. That's because the data is coming from server-side and we can't get hold of it to format it like we can on the Guest page.

**Comment by kswens1** [comment]
Tested and shared via Slack 11.29.2020
